// This file allows the game to load data without a web server.
// You can edit the content here directly.

const gameData = {
    regulations: [
        { id: 1, question: "依《緊急醫療救護法》，緊急醫療救護人員（EMT）分為哪三級？", answer: "初級（EMT-1）、中級（EMT-2）、高級（EMT-P）" },
        { id: 2, question: "現行規定 EMT-1 的訓練課程基準，其最低時數為多少小時？", answer: "56小時" },
        { id: 3, question: "EMT-1 證書的有效期限為幾年？", answer: "3年" },
        { id: 4, question: "EMT-1 欲展延證書效期，需在證書效期內接受多少小時的繼續教育？", answer: "24小時以上" },
        { id: 5, question: "救護人員在執行業務時，若發現傷病患疑似非病死或可疑為非病死者，應如何處理？", answer: "應報請當地警察機關處理（但仍應先送醫救治，不可拒送）" },
        { id: 6, question: "《緊急醫療救護法》第14-2條（好撒瑪利亞人條款），主要保障哪類人在急救時免負民事、刑事責任？", answer: "救護人員以外之人（民眾），於適用範圍內無償施救且無故意或重大過失者" },
        { id: 7, question: "救護車設置機關應將救護紀錄表保存至少幾年？", answer: "7年" },
        { id: 8, question: "依《緊急救護辦法》，救護車執行勤務時，車廂內應至少有幾名救護人員？", answer: "2名" },
        { id: 9, question: "救護車在什麼情況下，可以使用警鳴器及紅色閃光燈？", answer: "執行緊急醫療救護勤務，或運送緊急傷病患至醫療機構時" },
        { id: 10, question: "EMT-1 的業務範圍中，是否包含「靜脈注射」或「氣管內插管」？", answer: "不包含（此為 EMT-2 或 EMT-P 之範圍）" },
        { id: 11, question: "EMT-1 可以執行的核心急救處置包含哪些？（列舉常見三項）", answer: "生命徵象測量、CPR、AED使用、血糖量測、包紮止血、骨折固定、氧氣給予、頸椎固定等" },
        { id: 12, question: "救護車到達現場後，救護人員的首要任務是什麼？", answer: "確保現場安全（Scene Safety）" },
        { id: 13, question: "救護車將傷患送達醫療機構後，應與誰進行交接並簽名？", answer: "醫療機構之醫護人員" },
        { id: 14, question: "若發生大量傷病患（MCI）事故，當地救護資源無法負荷時，應向誰請求支援？", answer: "救災救護指揮中心" },
        { id: 15, question: "救護人員執行業務時，是否可以無故拒絕載送傷病患？", answer: "不得無故拒絕" },
        { id: 16, question: "非救護車是否可以標示「救護車」字樣或裝設警鳴器？", answer: "不可以，違反者將受罰鍰並扣牌" },
        { id: 17, question: "依《緊急救護辦法》，救護車分為哪兩類？", answer: "一般救護車、加護救護車" },
        { id: 18, question: "一般救護車應配置的救護人員資格為何？", answer: "應至少為兩名救護人員（其中一名可為救護車司機，但需具備EMT資格）" },
        { id: 19, question: "傷病患送達醫院後，救護紀錄表應如何處理？", answer: "一份留存醫院，一份帶回救護單位保存" },
        { id: 20, question: "當傷患意識清楚並拒絕送醫時，救護人員應如何處置？", answer: "給予充分告知風險，並請傷患或家屬簽署「拒絕送醫切結書」，並於救護紀錄表上註記" },
        { id: 21, question: "救護車車身顏色主要規定為何？", answer: "白色" },
        { id: 22, question: "救護車車身兩側應標示什麼內容？", answer: "設置機關（構）名稱及許可字號（若是捐贈車輛可標示捐贈者）" },
        { id: 23, question: "緊急醫療救護法的主管機關，在中央為？", answer: "衛生福利部" },
        { id: 24, question: "緊急醫療救護法的主管機關，在地方（直轄市、縣市）為？", answer: "直轄市、縣（市）政府（實際執行多為衛生局與消防局配合）" },
        { id: 25, question: "若救護人員在執行業務時，洩露傷病患之秘密，會受到什麼處罰？", answer: "行政罰鍰（依緊急醫療救護法）或刑法洩密罪" },
        { id: 26, question: "EMT-1 是否可以使用自動體外心臟電擊器 (AED)？", answer: "可以（這是 EMT-1 的核心技能）" },
        { id: 27, question: "EMT-1 是否可以操作手動電擊器 (Manual Defibrillator) 進行電擊？", answer: "不可以（這是 EMT-P 的範圍）" },
        { id: 28, question: "救護車內配置的氧氣組，應包含固定式與哪種型式？", answer: "攜帶式氧氣組" },
        { id: 29, question: "依規定，救護車應備有哪種擔架？", answer: "一般擔架（推床）及可折疊式或椅式擔架（樓梯椅）" },
        { id: 30, question: "救護車之消毒與清潔紀錄，應保存多久？", answer: "法規未明定消毒紀錄保存年限，但建議併同車輛維護紀錄保存" },
        { id: 31, question: "EMT-1 訓練合格證書由誰發給？", answer: "由中央衛生主管機關許可之發證機構（如消防署、教學醫院、相關協會等）發給" },
        { id: 32, question: "若 EMT-1 證書過期未展延，會有什麼後果？", answer: "證書失效，不得以 EMT 名義執行業務" },
        { id: 33, question: "救護車載送傷病患，原則上應送往哪裡的醫療機構？", answer: "就近適當之醫療機構" },
        { id: 34, question: "在大量傷病患現場，救護人員應優先執行什麼作業以決定後送順序？", answer: "檢傷分類 (Triage)" },
        { id: 35, question: "救護車執行勤務過路口時，遇到紅燈應如何行駛？", answer: "應開啟警示燈及警鳴器，減速確認安全後小心通過（雖有優先權但無絕對路權）" },
        { id: 36, question: "何謂「轉診」？", answer: "指傷病患經醫療機構診治後，因病情需要，轉送至其他醫療機構繼續接受治療" },
        { id: 37, question: "EMT-1 是否可以給予病患口服葡萄糖或舌下含片？", answer: "不可以（EMT-1 不得給予藥物，但可量測血糖）" },
        { id: 38, question: "若遇家屬要求將病患送往極遠處之特定醫院（非就近適當），救護人員應如何處理？", answer: "應向家屬說明病情危急程度及就近送醫原則，若家屬堅持且病情允許，需請指揮中心協調或簽署相關切結" },
        { id: 39, question: "救護人員在現場發現涉及刑案之證物（如刀械），應如何處理？", answer: "盡量避免觸碰或移動，並告知警方；若必須移動才能救護，應記錄移動前之位置" },
        { id: 40, question: "對於疑似傳染病病患，救護車使用後應進行什麼處理？", answer: "全車清潔與消毒" },
        { id: 41, question: "哪一層級的 EMT 可以執行「血糖監測」？", answer: "所有層級（包含 EMT-1）" },
        { id: 42, question: "救護車裝備中，是否強制要求配備「生產創傷包（OBS Kit）」？", answer: "是，依救護車裝備標準表，需配備生產包" },
        { id: 43, question: "若救護技術員受撤銷證書處分，多久內不得再受領該級證書？", answer: "依情節輕重而定，部分條款規定撤銷後不得重新請領" },
        { id: 44, question: "設置救護車之機關（構），若未依規定配置救護人員，會受到什麼處罰？", answer: "罰鍰並限期改善" },
        { id: 45, question: "緊急傷病患之定義為何？", answer: "指因疾病或受傷，危及生命或導致身體功能喪失，需立即給予醫療救護者" },
        { id: 46, question: "區域級以上醫院，應全天候提供什麼醫療服務？", answer: "緊急醫療服務" },
        { id: 47, question: "救護車除因情況緊急外，不得在何處停車？", answer: "非執行任務時需遵守交通規則" },
        { id: 48, question: "誰有權啟動大量傷病患救護機制？", answer: "救災救護指揮中心或現場指揮官" },
        { id: 49, question: "救護技術員資格證書遺失或損壞時，應如何處理？,向原發證機構或中央衛生主管機關申請補發或換發", answer: "向原發證機構或中央衛生主管機關申請補發或換發" },
        { id: 50, question: "救護紀錄表中，是否必須記錄「到達現場時間」與「離開現場時間」？", answer: "是，時間點紀錄對於責任釐清與品質管理至關重要" },
        { id: 51, question: "一般民眾若在公共場所設置 AED，是否需要向衛生主管機關登錄？", answer: "是，應登錄並上傳資訊" },
        { id: 52, question: "EMT-1 是否可以使用鼻咽呼吸道 (NPA)？", answer: "可以（這是 EMT-1 的基本呼吸道處置技術）" },
        { id: 53, question: "EMT-1 執行包紮止血時，若血液浸透第一層敷料，應如何處理？", answer: "直接在上方加蓋第二層敷料並加壓，不可移除第一層（避免破壞已形成的血塊）" },
        { id: 54, question: "救護車內的「血壓計」、「聽診器」屬於哪一類救護人員的必備技能裝備？", answer: "所有層級（包含 EMT-1）" },
        { id: 55, question: "救護車執行勤務時，駕駛員是否受酒精濃度限制？", answer: "是，絕對不得酒駕，標準同一般駕駛甚至更嚴格（職業駕駛標準）" },
        { id: 56, question: "若傷患為未成年人且無意識，現場無家屬，救護人員是否可以進行急救？", answer: "可以，基於「默示同意」（Implied Consent）原則" },
        { id: 57, question: "對於頸椎受傷疑慮的病患，EMT-1 應使用何種器材進行初步固定？", answer: "頸圈 (C-Collar) 及長背板 (Spine Board) 或相關固定器材" },
        { id: 58, question: "救護人員每幾年需要進行證書效期展延？", answer: "3年" },
        { id: 59, question: "緊急醫療救護法施行細則中，對於「偏遠地區」的救護車人員配置有何放寬規定？", answer: "得由救護人員一名及駕駛人員一名擔任（但駕駛若無EMT資格需受過急救訓練）" },
        { id: 60, question: "當現場環境對救護人員有立即且無法排除的生命威脅（如毒氣、坍塌、槍擊），應如何行動？", answer: "立即撤離至安全區域（Retreat），等待專業支援（如特搜、警方），不可貿然進入" }
    ],
    assessment: [
        { id: 1, question: "評估病患清醒程度的標準口訣是什麼？", answer: "AVPU（清、聲、痛、否）" },
        { id: 2, question: "AVPU 口訣中，V (Verbal) 代表的意識程度是什麼？", answer: "對聲音有反應（可與人對談，或對呼叫有反應）" },
        { id: 3, question: "AVPU 口訣中，P (Pain) 代表的意識程度是什麼？", answer: "對疼痛刺激有反應（例如捏壓指甲床或胸骨搓揉）" },
        { id: 4, question: "AVPU 口訣中，U (Unresponsive) 代表的意識程度是什麼？", answer: "對所有刺激（包括疼痛）均無反應" },
        { id: 5, question: "格拉斯哥昏迷指數 (GCS) 的三個評估要素是什麼？", answer: "眼睛反應 (E)、語言反應 (V)、運動反應 (M)" },
        { id: 6, question: "GCS 的最高分與最低分各是多少？", answer: "最高分15分，最低分3分" },
        { id: 7, question: "GCS 中，眼睛反應（E）評分最高分是多少？", answer: "4分（自發性張眼）" },
        { id: 8, question: "GCS 中，運動反應（M）評分最高分是多少？", answer: "6分（聽從指令動作）" },
        { id: 9, question: "GCS 評估中，何種分數通常視為重度創傷或需要立即插管的指標？", answer: "GCS ≤ 8分" },
        { id: 10, question: "對所有傷病患進行主觀病史詢問時，使用的標準口訣是什麼？", answer: "SAMPLE" },
        { id: 11, question: "SAMPLE 口訣中，A、M 分別代表什麼？", answer: "A：過敏史 (Allergies)；M：用藥史 (Medications)" },
        { id: 12, question: "SAMPLE 口訣中，P、L、E 分別代表什麼？", answer: "P：過去病史 (Past history)；L：最後進食時間 (Last oral intake)；E：事件 (Events leading to injury/illness)" },
        { id: 13, question: "評估病患疼痛嚴重度時，常用的口訣是什麼？", answer: "OPQRST" },
        { id: 14, question: "OPQRST 口訣中，P (Provocation) 代表詢問什麼？", answer: "誘發或緩解因素（做什麼動作會讓疼痛加劇或減輕？）" },
        { id: 15, question: "OPQRST 口訣中，Q (Quality) 代表詢問什麼？", answer: "疼痛的性質（是刺痛、悶痛、絞痛、還是壓迫感？）" },
        { id: 16, question: "OPQRST 口訣中，R (Region/Radiation) 代表詢問什麼？", answer: "疼痛區域及是否轉移或放射（痛點在哪裡？有沒有傳到其他地方？）" },
        { id: 17, question: "評估循環系統的標準動作包含哪三項？", answer: "檢查脈搏、評估膚色/膚溫/濕度、評估毛細血管充填時間 (CRT)" },
        { id: 18, question: "一般而言，成人毛細血管充填時間 (CRT) 應在幾秒內？", answer: "2秒內" },
        { id: 19, question: "當懷疑病患有休克時，評估脈搏強度應檢查哪一處？", answer: "橈動脈或頸動脈" },
        { id: 20, question: "在創傷評估的 Primary Survey 中，最重要的優先順序是什麼？", answer: "A（呼吸道）→ B（呼吸）→ C（循環/出血控制）" },
        { id: 21, question: "當病患有意識且說話清晰時，可推論其哪一項已暢通？", answer: "呼吸道 (Airway)" },
        { id: 22, question: "何種情況下，EMT 應立即懷疑有頸椎受損的可能性？", answer: "頭部或臉部創傷、車禍、高處墜落、無意識創傷病患" },
        { id: 23, question: "對於疑似頸椎受傷病患的呼吸道處置，應使用哪種手法開啟呼吸道？", answer: "下顎推舉法 (Jaw-thrust Maneuver)，避免頭部後仰" },
        { id: 24, question: "在評估呼吸時，應檢查哪三種面向？", answer: "呼吸速率、呼吸深度（或量）、呼吸音（有無雜音）" },
        { id: 25, question: "成人呼吸速率每分鐘多少次視為呼吸窘迫或過速？", answer: "大於20~24次/分" },
        { id: 26, question: "評估瞳孔時，應檢查哪三個要素？", answer: "大小 (Size)、對光反應 (Reactivity)、兩側是否對等 (Equality)" },
        { id: 27, question: "瞳孔評估口訣 PEARRL 中，P 代表什麼？", answer: "瞳孔 (Pupils)" },
        { id: 28, question: "瞳孔評估口訣 PEARRL 中，R (Reactivity) 代表什麼？", answer: "對光反應（是否收縮）" },
        { id: 29, question: "評估創傷病患時，應從何處開始進行系統性檢查？", answer: "從頭部開始，依序到頸部、胸部、腹部、骨盆、四肢，最後是背部（Primary Survey / Rapid Trauma Exam）" },
        { id: 30, question: "在評估骨盆時，檢查的標準手法是什麼？", answer: "輕柔地向內、向下壓或推擠骨盆，確認有無不穩定" },
        { id: 31, question: "在救護紀錄表上，記錄病患主訴（Chief Complaint）的重要性是什麼？", answer: "提供病患尋求醫療協助最直接的原因" },
        { id: 32, question: "當病患表現出防衛性或腹肌僵硬時，懷疑腹部有什麼問題？,腹部內出血或腹膜炎 (Peritonitis)", answer: "腹部內出血或腹膜炎 (Peritonitis)" },
        { id: 33, question: "在大量傷患現場，最常用的快速檢傷分類系統是什麼？", answer: "START（簡易檢傷與快速治療）" },
        { id: 34, question: "START 檢傷分類中，紅色標籤代表哪種等級？", answer: "立即處理（Immediate），需優先後送" },
        { id: 35, question: "START 檢傷分類中，綠色標籤代表哪種等級？", answer: "輕傷（Minor），可延後處理" },
        { id: 36, question: "START 檢傷分類中，若傷患呼吸速率超過每分鐘 30 次，應給予什麼標籤？", answer: "紅色（Immediate）" },
        { id: 37, question: "START 檢傷分類中，若傷患已無呼吸，經開放呼吸道後仍無呼吸，應給予什麼標籤？", answer: "黑色（Deceased），已死亡" },
        { id: 38, question: "評估肢體時，應檢查哪三個要素（3P）？", answer: "脈搏 (Pulse)、感覺 (Paresthesia)、運動 (Paralysis)" },
        { id: 39, question: "評估新生兒或嬰兒的休克狀態時，哪個指標比血壓更可靠？", answer: "心跳速率、膚色及毛細血管充填時間 (CRT)" },
        { id: 40, question: "評估病患皮膚濕度時，若皮膚摸起來冰冷、濕黏，可能暗示什麼狀態？", answer: "休克（血液灌流不足）" },
        { id: 41, question: "使用血糖機量測血糖時，EMT-1 應注意什麼（除了數值之外）？", answer: "量測部位是否清潔、試紙是否過期或受潮" },
        { id: 42, question: "評估呼吸音時，聽到「哮鳴音（Wheezing）」通常與哪種疾病有關？", answer: "氣喘 (Asthma) 或下呼吸道阻塞" },
        { id: 43, question: "評估呼吸音時，聽到「鼾音（Snoring）」可能暗示哪種問題？", answer: "舌根後墜或上呼吸道部分阻塞" },
        { id: 44, question: "對於胸痛病患，詢問過去病史時最需注意的是哪類疾病？", answer: "心臟病史（如心肌梗塞、心絞痛）、高血壓、糖尿病史" },
        { id: 45, question: "評估創傷現場時，MOI (Mechanism of Injury) 機制對評估的重要性是什麼？", answer: "幫助預測身體可能受傷的部位及嚴重程度（高能量創傷）" },
        { id: 46, question: "在神經學評估中，若病患出現一側肢體無力，這在 GCS 的運動反應評估中代表什麼意義？", answer: "可能屬於局部神經損傷，評分時以患肢最高能達到的指令動作程度給分" },
        { id: 47, question: "除了 GCS 外，對於懷疑酒醉或藥物中毒的病患，評估其意識程度的困難點是什麼？", answer: "可能無法準確反映潛在的腦部損傷，因為藥物會影響其清醒和語言反應" },
        { id: 48, question: "辛辛那提中風指標的英文縮寫口訣是什麼？", answer: "FAST" },
        { id: 49, question: "FAST 口訣中的 F 代表什麼評估？", answer: "Face（觀察臉部微笑時是否對稱、有無歪斜）" },
        { id: 50, question: "FAST 口訣中的 A 代表什麼評估？", answer: "Arm（觀察雙手平舉時是否有一側無力下垂）" },
        { id: 51, question: "FAST 口訣中的 S 代表什麼評估？", answer: "Speech（觀察說話是否清晰、有無含糊或失語）" },
        { id: 52, question: "FAST 口訣中的 T 代表什麼重點？", answer: "Time（確認最後目擊病人正常的時間 / 發作時間）" },
        { id: 53, question: "若 FAST 評估中出現任何一項異常，代表病人罹患中風的機率約為多少？", answer: "72% 以上" },
        { id: 54, question: "當懷疑病患中風時，除了 FAST，還必須優先測量哪一個生命徵象以排除類似症狀？", answer: "血糖（排除低血糖造成的類中風症狀）" },
        { id: 55, question: "在 GCS 評估中，若病患說話語無倫次、答非所問（Confused），V 項目得幾分？", answer: "4分" },
        { id: 56, question: "在 GCS 評估中，若病患只能發出呻吟聲、無法辨識單字（Incomprehensible sounds），V 項目得幾分？,2分", answer: "2分" },
        { id: 57, question: "疑似缺血性中風病患，若要在黃金時間內接受血栓溶解劑治療，通常需在發作幾小時內？", answer: "3小時（部分情況可至4.5小時，故EMT需盡快送醫）" },
        { id: 58, question: "一般成年人平靜狀態下的正常呼吸速率範圍為何？", answer: "每分鐘 12-20 次" },
        { id: 59, question: "一般成年人平靜狀態下的正常心跳速率範圍為何？", answer: "每分鐘 60-100 次" },
        { id: 60, question: "一般成年人的收縮壓 (SBP) 正常範圍約為何？", answer: "90-140 mmHg" },
        { id: 61, question: "一般成年人的舒張壓 (DBP) 正常範圍約為何？", answer: "60-90 mmHg" },
        { id: 62, question: "正常人的體溫（耳溫）範圍約為何？", answer: "36.5°C - 37.5°C" },
        { id: 63, question: "正常成人的空腹血糖值約為多少 mg/dL？", answer: "70-100 mg/dL (飯後通常不超過 140)" },
        { id: 64, question: "對於一般病患（非 COPD），血氧濃度 (SpO2) 低於多少通常建議給予氧氣？", answer: "94%" },
        { id: 65, question: "當成年人呼吸速率大於多少時，視為呼吸過速（Tachypnea）？", answer: "每分鐘 20 次以上（大於 29 次則為極度危險）" },
        { id: 66, question: "當成年人呼吸速率小於多少時，視為呼吸過慢（Bradypnea）？", answer: "每分鐘 10-12 次以下（小於 8 次需輔助呼吸）" },
        { id: 67, question: "當成年人心跳速率大於多少時，視為心搏過速（Tachycardia）？", answer: "每分鐘 100 次以上" },
        { id: 68, question: "當成年人心跳速率小於多少時，視為心搏過緩（Bradycardia）？", answer: "每分鐘 60 次以下" },
        { id: 69, question: "低血糖症（Hypoglycemia）的危急處置標準通常定義為血糖低於多少？", answer: "70 mg/dL（低於 60 mg/dL 且有症狀則必須立即處置）" },
        { id: 70, question: "高血糖急症（如 DKA/HHS）通常血糖會高於多少？", answer: "通常高於 250-300 mg/dL，甚至測不到 (High)" },
        { id: 71, question: "學齡前兒童（1-5歲）的正常心跳速率範圍約為何？", answer: "每分鐘 80-140 次" },
        { id: 72, question: "嬰兒（1歲以下）的正常心跳速率範圍約為何？", answer: "每分鐘 100-160 次" },
        { id: 73, question: "新生兒或嬰兒的呼吸速率範圍約為何？", answer: "每分鐘 30-60 次" },
        { id: 74, question: "估算 1-10 歲兒童「低血壓」收縮壓下限的公式為何？", answer: "70 + (2 × 年齡) mmHg" },
        { id: 75, question: "對於兒童或嬰兒，若心跳小於每分鐘 60 次且伴隨灌流不足徵象，應如何處置？", answer: "視同心跳停止，立即開始 CPR" },
        { id: 76, question: "危急創傷病患（Major Trauma）的呼吸速率標準為何？", answer: "每分鐘 < 10 或 > 29 次" },
        { id: 77, question: "危急創傷病患的收縮壓標準為何？", answer: "收縮壓 < 90 mmHg" },
        { id: 78, question: "危急創傷病患的 GCS 昏迷指數標準為何？", answer: "GCS < 13 分（部分標準為 < 14）" },
        { id: 79, question: "從高處墜落，成人高度超過多少公尺視為高能量創傷？", answer: "6 公尺（或約 2 層樓高）" },
        { id: 80, question: "從高處墜落，小兒高度超過多少視為高能量創傷？", answer: "3 公尺（或身高 2-3 倍以上）" },
        { id: 81, question: "休克指數 (Shock Index) 的計算公式為何？", answer: "心跳速率 (HR) ÷ 收縮壓 (SBP)" },
        { id: 82, question: "正常的休克指數 (Shock Index) 應小於多少？", answer: "小於 1.0（通常約 0.5-0.7，若 > 1.0 代表有休克風險）" },
        { id: 83, question: "微血管充填時間 (CRT) 超過幾秒視為異常（灌流不足）？", answer: "2 秒" },
        { id: 84, question: "身體單側（如整隻手臂）燒燙傷面積佔比為多少？", answer: "9%" },
        { id: 85, question: "身體單側（如整隻大腿+小腿）燒燙傷面積佔比為多少？", answer: "18%" },
        { id: 86, question: "小兒（嬰幼兒）頭部佔身體表面積的比例約為多少？", answer: "18%（成人僅 9%，小兒頭大身體小）" },
        { id: 87, question: "格拉斯哥昏迷指數 (GCS) 低於幾分通常建議需要進階呼吸道（如插管）保護？", answer: "8 分或以下 (GCS ≤ 8)" },
        { id: 88, question: "車禍時，車輛變形凹陷深度超過多少公分，視為高能量撞擊機制？", answer: "車體變形 > 50 公分，或車室內變形 > 30 公分" },
        { id: 89, question: "若同車乘客有死亡，其他乘客是否視為危急個案？", answer: "是，視為高能量創傷機制" },
        { id: 90, question: "在大量傷患檢傷分類 (START) 中，若微血管充填時間 (CRT) > 2 秒，應標示為何種顏色？", answer: "紅色（立即處理）" },
        { id: 91, question: "正常成人的脈搏壓 (Pulse Pressure) 約為多少？", answer: "30-50 mmHg（收縮壓減去舒張壓）" },
        { id: 92, question: "脈搏壓過窄（< 30 mmHg）通常暗示什麼狀況？", answer: "心包膜填塞、張力性氣胸或早期休克" },
        { id: 93, question: "脈搏壓過寬（> 60 mmHg）可能暗示什麼狀況？", answer: "顱內壓升高 (IICP)" },
        { id: 94, question: "庫興氏徵候 (Cushing's Triad) 顯示顱內壓升高的三大徵象數據變化為何？", answer: "血壓上升（高血壓）、心跳變慢（心搏過緩）、呼吸不規則" },
        { id: 95, question: "一氧化碳 (CO) 中毒時，血液中 COHb 濃度若大於多少會開始出現明顯中毒症狀？", answer: "通常 > 20%（吸菸者可能本來就高一點，但 >20% 為明顯異常）" },
        { id: 96, question: "體溫高於多少通常定義為發燒？", answer: "38°C" },
        { id: 97, question: "嚴重低體溫 (Hypothermia) 通常指中心體溫低於多少？", answer: "30°C（此時心臟極不穩定）" },
        { id: 98, question: "到院前預警指標 (MASS) 中，收縮壓小於多少是預警指標？", answer: "90 mmHg" },
        { id: 99, question: "新生兒出生後，Apgar Score 滿分是多少？,10 分", answer: "10 分" },
        { id: 100, question: "Apgar Score 評估項目包含哪五項？", answer: "外觀(膚色)、脈搏、皺眉(反射)、活動力(張力)、呼吸" },
        { id: 101, question: "若病患心跳每分鐘 150 次以上（成人），且為窄QRS波，通常懷疑為何種心律？", answer: "陣發性室上性心搏過速 (PSVT)" },
        { id: 102, question: "若病患心跳極慢（< 50 bpm）且出現頭暈、胸痛、低血壓，這屬於什麼狀況？", answer: "不穩定型心搏過緩 (Unstable Bradycardia)" },
        { id: 103, question: "腹部急症中，若腹主動脈寬度超過多少可能懷疑有動脈瘤 (AAA)？", answer: "雖然 EMT 無法掃描，但若觸診發現明顯搏動性腫塊需高度懷疑（正常直徑約 2-3 cm）" },
        { id: 104, question: "對於 COPD 病患，若使用高濃度氧氣，可能會抑制其呼吸驅動力，SpO2 應維持在？", answer: "88-92%" },
        { id: 105, question: "創傷失血量評估：骨盆骨折可能造成內出血達多少量？", answer: "500 - 3000 ml（甚至更多，是致死主因）" },
        { id: 106, question: "創傷失血量評估：一側股骨（大腿骨）骨折可能造成失血量約多少？", answer: "1000 - 1500 ml" },
        { id: 107, question: "哪一種休克通常會表現出「心跳快」但「皮膚溫暖、乾燥」？", answer: "神經性休克 (Neurogenic Shock) 初期，或敗血性休克早期" }
    ],
    methods: [
        { id: 1, question: "成人 CPR 的按壓速率範圍為何？", answer: "每分鐘 100-120 次" },
        { id: 2, question: "成人 CPR 的按壓深度建議為何？", answer: "至少 5 公分，但不超過 6 公分" },
        { id: 3, question: "成人 CPR 的按壓與吹氣比例（單人與雙人）為何？", answer: "皆為 30:2" },
        { id: 4, question: "執行高品質 CPR 的五大要點為何？", answer: "速率夠快、深度夠深、胸回彈完全、減少中斷、避免過度換氣" },
        { id: 5, question: "兩名 EMT 在現場執行 CPR 時，建議每幾分鐘或幾個循環交換按壓者？", answer: "每 2 分鐘或 5 個循環" },
        { id: 6, question: "AED 貼片黏貼的標準位置（成人）為何？", answer: "右鎖骨下方、左乳頭外側（右上左下）" },
        { id: 7, question: "如果病患胸部有毛髮導致 AED 貼片無法服貼，應如何處理？", answer: "用力撕下第一片以拔除毛髮（或使用刮刀），再貼上新的貼片" },
        { id: 8, question: "AED 分析心律時，最重要的動作是什麼？", answer: "確保無人接觸病患（Clear）" },
        { id: 9, question: "對於有裝設心律調節器（Pacemaker）的病患，AED 貼片應如何貼？", answer: "避開調節器隆起處至少 2.5 公分（約一指幅）" },
        { id: 10, question: "嬰兒（1歲以下）CPR 的按壓位置為何？", answer: "兩乳頭連線下方（胸骨下半部）" },
        { id: 11, question: "嬰兒 CPR 若為雙人操作，按壓手法應改為何種？", answer: "雙手環抱拇指按壓法 (2-Thumb-Encircling Hands)" },
        { id: 12, question: "測量口咽呼吸道 (OPA) 大小的標準方法為何？", answer: "嘴角至耳垂 或 下顎角" },
        { id: 13, question: "插入成人 OPA 的標準手法為何？", answer: "開口朝向硬顎置入，通過懸雍垂後旋轉 180 度" },
        { id: 14, question: "使用口咽呼吸道 (OPA) 的主要禁忌症為何？", answer: "病患有嘔吐反射 (Gag Reflex)" },
        { id: 15, question: "測量鼻咽呼吸道 (NPA) 大小的標準方法為何？", answer: "鼻尖至耳垂" },
        { id: 16, question: "插入 NPA 時，斜切面 (Bevel) 應朝向何處？,朝向鼻中膈 (Septum)", answer: "朝向鼻中膈 (Septum)" },
        { id: 17, question: "使用 NPA 的主要禁忌症為何？", answer: "嚴重臉部創傷（疑似顱底骨折）或有腦脊髓液流出" },
        { id: 18, question: "使用抽吸管 (Suction) 清除口鼻分泌物時，成人每次抽吸時間不應超過幾秒？", answer: "15秒" },
        { id: 19, question: "抽吸的正確操作順序為何？", answer: "先插入至預定深度（不按抽吸孔），邊抽吸邊旋轉邊退出" },
        { id: 20, question: "使用鼻導管 (Nasal Cannula) 給氧，建議流速範圍為何？", answer: "1-6 LPM (L/min)" },
        { id: 21, question: "使用非再呼吸面罩 (NRM) 給氧，流速至少需多少才能確保儲氣袋充盈？", answer: "10-15 LPM (通常開 12-15 LPM)" },
        { id: 22, question: "使用 BVM (袋瓣面罩) 給氧時，單手扣面罩的標準手法為何？", answer: "EC 手法 (EC Clamp)" },
        { id: 23, question: "創傷出血的第一線止血方法為何？", answer: "直接加壓止血法 (Direct Pressure)" },
        { id: 24, question: "若四肢大出血且直接加壓無效，EMT-1 應使用何種器材？", answer: "止血帶 (Tourniquet, 如 CAT)" },
        { id: 25, question: "止血帶應綁在傷口的哪個位置？", answer: "傷口近心端約 5-10 公分處（避開關節），或直接綁在肢體最根部" },
        { id: 26, question: "止血帶旋緊後，什麼時候可以鬆開？", answer: "到院前原則上不鬆開（除非醫師指示）" },
        { id: 27, question: "對於腹部臟器外露的處置原則為何？", answer: "使用生理食鹽水潤濕的無菌敷料覆蓋，再蓋上保鮮膜或防水材質保溫，不可將臟器推回" },
        { id: 28, question: "對於穿刺物（如刀子插在胸口）的處置原則為何？", answer: "原則上不拔除，並進行固定，除非阻礙 CPR 進行或影響呼吸道" },
        { id: 29, question: "懷疑頸椎受傷病患，最重要的第一步處置為何？", answer: "徒手頸椎限制（頭頸部固定），直到器材固定完成" },
        { id: 30, question: "測量頸圈 (C-Collar) 大小的標準方法為何？", answer: "下顎角至斜方肌前緣的指幅寬度" },
        { id: 31, question: "上頸圈時，若病患頸部有空隙，應如何處理？", answer: "不可硬塞，應調整頸圈大小或選擇合適尺寸，確保支撐力" },
        { id: 32, question: "將病患固定於長背板 (Long Spine Board) 的操作口訣或順序通常為何？", answer: "身體（軀幹）先固定，頭部最後固定" },
        { id: 33, question: "在長背板上固定軀幹時，綁帶的重點位置有哪三處？", answer: "胸部、骨盆（髂骨）、大腿" },
        { id: 34, question: "使用脫困擔架 (Scoop Stretcher) 的主要優點為何？", answer: "不需移動病患太多即可鏟起，適用於骨盆骨折或不宜翻身之病患" },
        { id: 35, question: "KED (肯德用脫困背心) 主要用於何種情境？", answer: "狀況穩定且受困於坐姿（如車禍受困駕駛）的病患" },
        { id: 36, question: "操作 KED 時，綁帶固定的口訣順序為何？", answer: "中-下-腿-頭-上 (My Baby Looks Hot Tonight)" },
        { id: 37, question: "KED 固定完畢後，若要將病患移出車外，應先鬆開哪裡的綁帶？", answer: "腿部綁帶（避免影響腿部伸展或勾住）" },
        { id: 38, question: "若車禍現場病患狀況危急（如心跳停止或車輛起火），應採取何種搬運法？", answer: "快速脫困法 (Rapid Extrication)，不使用 KED，直接上長背板" },
        { id: 39, question: "脫除全罩式安全帽時，需要幾名救護人員操作？", answer: "至少 2 名（一人負責固定頭頸，一人負責脫除）" },
        { id: 40, question: "在脫除安全帽的過程中，最重要的原則是什麼？", answer: "全程保持頸椎中立，不可晃動頭部" },
        { id: 41, question: "處理斷肢（Amputation）時，斷肢應如何保存？", answer: "用生理食鹽水紗布包裹，置於塑膠袋內密封，再放入冰水中（不可直接接觸冰塊或浸泡水中）" },
        { id: 42, question: "燒燙傷面積評估，成人單側整隻手臂約佔多少百分比？", answer: "9% (九則運算法)" },
        { id: 43, question: "化學燒傷（如強酸強鹼潑灑）的現場第一優先處置為何？,大量清水沖洗至少 20 分鐘（若是乾粉需先掃掉再沖）", answer: "大量清水沖洗至少 20 分鐘（若是乾粉需先掃掉再沖）" },
        { id: 44, question: "對於骨折部位進行固定的原則為何？", answer: "固定範圍需涵蓋骨折處的上、下兩個關節" },
        { id: 45, question: "固定骨折前、後，都必須檢查什麼？", answer: "末端的 PMS (脈搏、運動、感覺)" },
        { id: 46, question: "在翻身（Log Roll）操作中，由誰負責發號施令？", answer: "位於頭部固定頸椎的救護人員" },
        { id: 47, question: "對於無外傷但意識不清的病患，若無頸椎疑慮，應採何種姿勢運送？", answer: "復甦姿勢 (Recovery Position) / 側躺" },
        { id: 48, question: "使用氧氣鋼瓶時，開啟鋼瓶閥門應避開哪個位置？", answer: "出氣口（避免氣體高速衝出傷人）" },
        { id: 49, question: "當氧氣鋼瓶壓力低於多少 psi 時，建議更換新瓶（安全殘壓）？", answer: "200-500 psi (一般建議 500 psi 即更換)" },
        { id: 50, question: "給予口服葡萄糖粉/漿的適應症為何？", answer: "意識清楚且有吞嚥能力的低血糖病患" },
        { id: 51, question: "過度換氣症候群 (Hyperventilation) 病患，是否可以使用紙袋罩住口鼻呼吸？", answer: "不建議（可能造成缺氧，應引導其減緩呼吸頻率）" },
        { id: 52, question: "若病患因異物哽塞無法發聲且意識清楚，應立即執行何種急救法？", answer: "哈姆立克法 (Heimlich Maneuver) / 腹部推擠法" },
        { id: 53, question: "若哈姆立克法操作中病患失去意識，應立即改為執行什麼？", answer: "CPR（查看口腔有無異物，若有則挖出，無則吹氣按壓）" },
        { id: 54, question: "對於懷孕末期或明顯肥胖的異物哽塞病患，哈姆立克法應改按壓哪裡？", answer: "胸部（胸部推擠法）" },
        { id: 55, question: "清洗開放性傷口時，應使用何種液體？", answer: "無菌生理食鹽水 (Normal Saline)" },
        { id: 56, question: "對於眼睛化學灼傷的沖洗方向為何？", answer: "由內眼角向外眼角沖洗" },
        { id: 57, question: "測量血壓時，壓脈帶應綁在哪個位置？", answer: "肘窩上方約 2.5 公分處" },
        { id: 58, question: "聽診血壓時，第一聲聽到的聲音代表什麼壓？", answer: "收縮壓 (Systolic pressure)" },
        { id: 59, question: "長背板固定後，為何需要再次評估四肢感覺與運動功能？", answer: "確認固定帶是否過緊壓迫神經或血管" },
        { id: 60, question: "在搬運病患下樓梯時，擔架頭端應朝上還是朝下？", answer: "頭端朝上（頭高腳低），由腳端先下" },
        { id: 61, question: "使用血氧機 (SpO2) 時，什麼情況下容易造成數值誤判或無法讀取？", answer: "塗指甲油、手部冰冷、一氧化碳中毒（會呈現假性高數值）、休克" },
        { id: 62, question: "對於慢性阻塞性肺病 (COPD) 病患，血氧濃度 (SpO2) 目標通常設定在多少？", answer: "88% - 92%（避免抑制缺氧驅動力）" },
        { id: 63, question: "嬰兒（1歲以下）的氣道開放姿勢應維持在什麼狀態？,嗅吸姿勢 (Sniffing Position)，可於肩部下方墊毛巾，不可過度後仰", answer: "嗅吸姿勢 (Sniffing Position)，可於肩部下方墊毛巾，不可過度後仰" },
        { id: 64, question: "檢查嬰兒（1歲以下）脈搏的首選位置是哪裡？", answer: "肱動脈 (Brachial Artery，上臂內側)" },
        { id: 65, question: "嬰兒（1歲以下）發生異物哽塞且意識清楚時，應採取何種急救法？", answer: "背部拍打 5 次 + 胸部推擠 5 次 (Back Slaps & Chest Thrusts)" },
        { id: 66, question: "懷孕後期（大於20週）的創傷病患，在長背板固定後應如何擺位以避免低血壓？", answer: "將長背板向左側傾斜（或墊高右側），避免子宮壓迫下腔靜脈" },
        { id: 67, question: "流鼻血 (Epistaxis) 病患的正確處置姿勢為何？", answer: "坐姿，身體微向前傾，捏住鼻翼兩側（不可後仰）" },
        { id: 68, question: "牙齒脫落 (Tooth Avulsion) 時，掉落的牙齒應保存在何種液體中最為理想？", answer: "冰牛奶、生理食鹽水或病患自己的口水中（不可刷洗牙根）" },
        { id: 69, question: "開放性氣胸 (Sucking Chest Wound) 的緊急處置為何？", answer: "使用三面貼紮的密封敷料或專用胸腔貼片 (Chest Seal)" },
        { id: 70, question: "若異物穿刺在臉頰且造成呼吸道阻塞或大量出血難以控制，是否可以拔除？", answer: "可以（這是少數可以拔除穿刺物的情況之一），並將傷口兩側都壓迫止血" },
        { id: 71, question: "被毒蛇咬傷時，傷處應如何擺放？", answer: "低於心臟高度，並固定肢體避免活動" },
        { id: 72, question: "被蜜蜂螫傷若留下毒針，應如何移除？", answer: "用鈍器（如信用卡）刮除，不可用手擠壓毒囊" },
        { id: 73, question: "熱中暑 (Heat Stroke) 與熱衰竭的主要區別症狀為何？", answer: "熱中暑通常意識改變且皮膚乾熱（無汗）；熱衰竭通常意識清楚且皮膚濕冷" },
        { id: 74, question: "對於嚴重失溫 (Hypothermia) 的病患，檢查脈搏的時間應延長至幾秒？", answer: "30 - 45 秒（因為心跳可能極其微弱且緩慢）" },
        { id: 75, question: "當病患正在全身性癲癇發作 (Seizure) 時，EMT 的主要處置為何？", answer: "保護病患頭部避免碰撞受傷，不可強行壓制肢體，不可塞東西入口中" },
        { id: 76, question: "癲癇發作結束後 (Post-ictal)，病患通常意識不清且有分泌物，應採何種姿勢？", answer: "復甦姿勢 (側臥)，並清除口中分泌物" },
        { id: 77, question: "對於休克 (Shock) 病患的標準急救姿勢為何？", answer: "平躺 (Supine)，並給予保暖（不再建議抬高下肢）" },
        { id: 78, question: "若需約束暴力或精神急症病患，絕對禁止採何種姿勢？", answer: "趴臥 (Prone)，以免造成姿勢性窒息" },
        { id: 79, question: "遇到疑似一氧化碳 (CO) 中毒的病患，其 SpO2 數值通常呈現為何？", answer: "正常或偏高（因為儀器無法分辨 CO 與 O2），故不可依賴 SpO2 判斷" },
        { id: 80, question: "在車禍現場若發現病患雖然清醒但頸部疼痛，應在何時上頸圈？", answer: "在完成頭頸部徒手固定並評估頸部後，儘早套上" },
        { id: 81, question: "使用氧氣面罩時，若病患發生嘔吐，首要動作為何？", answer: "立即取下面罩並將病患翻身側臥進行抽吸" },
        { id: 82, question: "若在 CPR 過程中發現病患腹部嚴重脹氣，是否應該按壓腹部排氣？", answer: "不可以，這會導致胃內容物逆流造成吸入性肺炎，應重新調整呼吸道角度" },
        { id: 83, question: "對於氣切造口 (Stoma) 病患進行人工呼吸時，BVM 應接在哪裡？", answer: "直接接在氣切管上，或使用嬰兒面罩罩住造口" },
        { id: 84, question: "氧氣鋼瓶每幾年需要進行一次水壓測試？", answer: "每 3 年" },
        { id: 85, question: "對於不穩定病患，生命徵象應每幾分鐘評估一次？", answer: "每 5 分鐘" },
        { id: 86, question: "對於狀況穩定病患，生命徵象應每幾分鐘評估一次？", answer: "每 15 分鐘" },
        { id: 87, question: "救護紀錄表寫錯字時，應如何修改？", answer: "在錯字上畫單一刪除線，修正後在旁簽名或蓋章（不可塗改或用立可帶）" },
        { id: 88, question: "若病患眼睛有異物感，是否可以請病患揉眼睛？", answer: "絕對不可以，應覆蓋雙眼限制眼球轉動並送醫" },
        { id: 89, question: "若要為小兒（8歲以下）使用 AED，但現場只有成人貼片，應如何處理？", answer: "依然可以使用成人貼片，採「前胸後背」方式黏貼" },
        { id: 90, question: "孕婦心跳停止進行 CPR 時，除了標準流程外，還需多做哪個動作？", answer: "徒手將子宮向左推（左側子宮推移），以減輕下腔靜脈壓迫" },
        { id: 91, question: "在火場或濃煙環境救出的病患，即使沒有燒傷，也必須優先懷疑什麼？", answer: "呼吸道灼傷及一氧化碳/氰化物中毒" },
        { id: 92, question: "若病患僅單眼受傷，包紮時建議如何處理？", answer: "原則上包紮雙眼，以減少眼球連動造成的二次傷害（視情況與病患溝通，若病患極度恐慌可保留健側視野但囑咐勿轉動）" },
        { id: 93, question: "乾粉狀化學物質灼傷（如生石灰），沖水前必須先做什麼？", answer: "先將粉末掃掉或拍掉（避免遇水生熱加劇傷害）" },
        { id: 94, question: "電擊傷病患除了體表燒傷外，必須特別監測什麼？", answer: "心律（電擊易導致心律不整）" },
        { id: 95, question: "斷肢保存時，為何不能直接接觸冰塊？", answer: "會造成組織凍傷，降低接回成功率" },
        { id: 96, question: "當執行 Log Roll 翻身時，位於身體側邊的施救者應採何種姿勢？", answer: "雙膝跪地或高跪姿，緊貼病患身體" },
        { id: 97, question: "在到院前，若病患出現過敏性休克 (Anaphylaxis) 徵候，EMT-1 最重要的處置是什麼？", answer: "給予高濃度氧氣，盡速送醫（若有 EpiPen 協助病患使用）" },
        { id: 98, question: "若病患頭部外傷且耳鼻流出清澈液體（腦脊髓液），應如何處置？", answer: "不可填塞，用無菌紗布鬆鬆覆蓋在耳鼻外吸附液體即可" },
        { id: 99, question: "大量傷病患檢傷分類中，若傷患無呼吸，打開呼吸道後仍無呼吸，給予什麼顏色卡？", answer: "黑色 (Black) / 死亡" },
        { id: 100, question: "如果在現場發現已經有屍僵 (Rigor Mortis) 或屍斑 (Livor Mortis) 的病患，是否需要進行 CPR？", answer: "不需要，這是不建議施救的明顯死亡徵象" }
    ]
};
